Repository tb1337/paperless-api, pull requests merged in 2024-05, with the labels that each got.

#181 Remove unused noqa directive
  poetry.lock
  src/pypaperless/models/documents.py
Labels: ci

#183 Fix permissions are not requested by pages()/reduce()
  src/pypaperless/models/mixins/helpers/callable.py
  src/pypaperless/models/mixins/helpers/iterable.py
  tests/test_models_matrix.py
Labels: bugfix

#184 Remove replace tz to Z
  src/pypaperless/models/utils/__init__.py
  tests/data/v0_0_0.py
  tests/data/v1_17_0.py
  tests/data/v2_0_0.py
  tests/data/v2_6_0.py
Labels: refactor, skip-changelog

#199 Remove text_color from TagDraft required_fields
  src/pypaperless/models/classifiers.py
Labels: bugfix

#206 Do not quote Multipart fields in forms
  src/pypaperless/api.py
Labels: bugfix
