Repository tb1337/paperless-api, pull requests merged in 2025-08, with the labels that each got.

#486 Remove remote endpoint checking
  pypaperless/api.py
  pypaperless/models/base.py
  pypaperless/models/classifiers.py
  pypaperless/models/config.py
  pypaperless/models/custom_fields.py
  pypaperless/models/documents.py
  pypaperless/models/mails.py
  pypaperless/models/permissions.py
  pypaperless/models/remote_version.py
  pypaperless/models/saved_views.py
  pypaperless/models/share_links.py
  pypaperless/models/statistics.py
  pypaperless/models/status.py
  pypaperless/models/tasks.py
  pypaperless/models/workflows.py
  tests/test_common.py
Labels: refactor

#487 Raise api version
  pypaperless/const.py
Labels: bugfix

#483 fix parsing created date (fixes #482)
  pypaperless/models/utils/__init__.py
Labels: bugfix

#504 Update README.md
  README.md
Labels: documentation, major
