Repository tb1337/paperless-api, pull requests merged in 2025-05, with the labels that each got.

#418 removed header update on session
  pypaperless/api.py
Labels: bugfix

#419 Add statistics api endpoint
  pypaperless/api.py
  pypaperless/const.py
  pypaperless/helpers.py
  pypaperless/models/__init__.py
  pypaperless/models/common.py
  pypaperless/models/share_links.py
  pypaperless/models/statistics.py
  tests/data/__init__.py
  tests/data/v2_15_0.py
  tests/test_models_specific.py
Labels: new-feature

#420 Add missing fields and statustype to status endpoint
  pypaperless/models/common.py
Labels: enhancement

#421 Add remote version endpoint
  pypaperless/api.py
  pypaperless/const.py
  pypaperless/helpers.py
  pypaperless/models/__init__.py
  pypaperless/models/remote_version.py
  tests/data/__init__.py
  tests/data/v0_0_0.py
  tests/test_models_specific.py
Labels: new-feature

#422 Add errors for bad authentication
  pypaperless/api.py
  pypaperless/exceptions.py
  tests/conftest.py
  tests/test_common.py
Labels: enhancement
